easy_questions = [

    # 🟢 EASY
    {"question": "What is 2 + 2?", "answer": "4", "difficulty": "easy"},
    {"question": "What color is the sun?", "answer": "yellow", "difficulty": "easy"},
    {"question": "How many days are in a week?", "answer": "7", "difficulty": "easy"},
    {"question": "What is the capital of France?", "answer": "paris", "difficulty": "easy"},
    {"question": "What animal says 'moo'?", "answer": "cow", "difficulty": "easy"},
    {"question": "What is the opposite of cold?", "answer": "hot", "difficulty": "easy"},
    {"question": "What is 10 minus 3?", "answer": "7", "difficulty": "easy"},
    {"question": "What planet do humans live on?", "answer": "earth", "difficulty": "easy"},
    {"question": "How many hours are in one day?", "answer": "24", "difficulty": "easy"},
    {"question": "What shape has four equal sides?", "answer": "square", "difficulty": "easy"},
    {"question": "What color are bananas when ripe?", "answer": "yellow", "difficulty": "easy"},
    {"question": "What is the capital of Japan?", "answer": "tokyo", "difficulty": "easy"},
    {"question": "How many letters are in the English alphabet?", "answer": "26", "difficulty": "easy"},
    {"question": "What is frozen water called?", "answer": "ice", "difficulty": "easy"},
    {"question": "What gas do humans breathe in to survive?", "answer": "oxygen", "difficulty": "easy"},
    {"question": "What is the atomic number of carbon?", "answer": "6", "difficulty": "hard"},
    {"question": "How many wheels does a bicycle have?", "answer": "2", "difficulty": "easy"},
    {"question": "What color is milk?", "answer": "white", "difficulty": "easy"},
    {"question": "What shape has three sides?", "answer": "triangle", "difficulty": "easy"},
    {"question": "What is 9 + 1?", "answer": "10", "difficulty": "easy"},
    {"question": "What day comes after Monday?", "answer": "tuesday", "difficulty": "easy"},
    {"question": "How many fingers does a human hand have?", "answer": "5", "difficulty": "easy"},
    {"question": "What is the capital of Germany?", "answer": "berlin", "difficulty": "easy"},
    {"question": "What animal gives milk?", "answer": "cow", "difficulty": "easy"},
    {"question": "What is 8 minus 3?", "answer": "5", "difficulty": "easy"},
    {"question": "What color is the sky on a clear day?", "answer": "blue", "difficulty": "easy"},
]
medium_questions = [
    # 🟡 MEDIUM
    {"question": "Who wrote the play Hamlet?", "answer": "shakespeare", "difficulty": "medium"},
    {"question": "What is the square root of 144?", "answer": "12", "difficulty": "medium"},
    {"question": "Which planet is known as the red planet?", "answer": "mars", "difficulty": "medium"},
    {"question": "What is 15 multiplied by 6?", "answer": "90", "difficulty": "medium"},
    {"question": "What is the capital of Canada?", "answer": "ottawa", "difficulty": "medium"},
    {"question": "Which ocean is the largest?", "answer": "pacific", "difficulty": "medium"},
    {"question": "How many continents are there on Earth?", "answer": "7", "difficulty": "medium"},
    {"question": "What is the chemical symbol for water?", "answer": "h2o", "difficulty": "medium"},
    {"question": "Who painted the Mona Lisa?", "answer": "leonardo da vinci", "difficulty": "medium"},
    {"question": "What is the boiling point of water in degrees Celsius?", "answer": "100", "difficulty": "medium"},
    {"question": "Which country invented paper?", "answer": "china", "difficulty": "medium"},
    {"question": "What is the largest mammal?", "answer": "blue whale", "difficulty": "medium"},
    {"question": "How many sides does a hexagon have?", "answer": "6", "difficulty": "medium"},
    {"question": "Which organ pumps blood through the body?", "answer": "heart", "difficulty": "medium"},
    {"question": "What is the capital of Egypt?", "answer": "cairo", "difficulty": "medium"},
    {"question": "How many bits are in one byte?", "answer": "8", "difficulty": "hard"},
    {"question": "What is the value of pi rounded to two decimal places?", "answer": "3.14", "difficulty": "hard"},
    {"question": "What gas is produced during photosynthesis?", "answer": "oxygen", "difficulty": "hard"},
    {"question": "What is the base of the natural logarithm?", "answer": "e", "difficulty": "hard"},
    {"question": "What is the speed of light in vacuum in meters per second?", "answer": "299792458", "difficulty": "hard"},
    {"question": "What is the square root of 169?", "answer": "13", "difficulty": "medium"},
    {"question": "Which planet has the most moons?", "answer": "saturn", "difficulty": "medium"},
    {"question": "What is the capital of South Korea?", "answer": "seoul", "difficulty": "medium"},
    {"question": "Who wrote the novel 1984?", "answer": "george orwell", "difficulty": "medium"},
    {"question": "What is the chemical symbol for sodium?", "answer": "na", "difficulty": "medium"},
    {"question": "How many continents are there on Earth?", "answer": "7", "difficulty": "medium"},
    {"question": "What is the boiling point of water in degrees Celsius?", "answer": "100", "difficulty": "medium"},
    {"question": "Which element has the atomic number 8?", "answer": "oxygen", "difficulty": "medium"},
    {"question": "What is the largest ocean on Earth?", "answer": "pacific", "difficulty": "medium"},
    {"question": "What is the capital of Argentina?", "answer": "buenos aires", "difficulty": "medium"},
    {"question": "What is 17 multiplied by 6?", "answer": "102", "difficulty": "medium"},
    {"question": "Who painted the Mona Lisa?", "answer": "leonardo da vinci", "difficulty": "medium"},
    {"question": "What gas do plants absorb during photosynthesis?", "answer": "carbon dioxide",
     "difficulty": "medium"},
    {"question": "What is the currency of Japan?", "answer": "yen", "difficulty": "medium"},
    {"question": "How many degrees are in a straight angle?", "answer": "180", "difficulty": "medium"},
]
hard_questions = [
    # 🔴 HARD
    {"question": "What year did World War II end?", "answer": "1945", "difficulty": "hard"},
    {"question": "Who developed the theory of general relativity?", "answer": "einstein", "difficulty": "hard"},
    {"question": "What is the chemical symbol for potassium?", "answer": "k", "difficulty": "hard"},
    {"question": "What is the capital of Iceland?", "answer": "reykjavik", "difficulty": "hard"},
    {"question": "What is the derivative of x squared?", "answer": "2x", "difficulty": "hard"},
    {"question": "How many bones are in the adult human body?", "answer": "206", "difficulty": "hard"},
    {"question": "What is the hardest natural substance on Earth?", "answer": "diamond", "difficulty": "hard"},
    {"question": "Which scientist proposed the laws of motion?", "answer": "newton", "difficulty": "hard"},
    {"question": "What is the capital of Mongolia?", "answer": "ulaanbaatar", "difficulty": "hard"},
    {"question": "What gas has the chemical formula co2?", "answer": "carbon dioxide", "difficulty": "hard"},
    {"question": "What is the smallest prime number?", "answer": "2", "difficulty": "hard"},
    {"question": "What is the largest planet in the solar system?", "answer": "jupiter", "difficulty": "hard"},
    {"question": "Which element has the atomic number 1?", "answer": "hydrogen", "difficulty": "hard"},
    {"question": "What is the capital of New Zealand?", "answer": "wellington", "difficulty": "hard"},
    {"question": "How many degrees are in a right angle?", "answer": "90", "difficulty": "hard"},
    {"question": "Which programming language is primarily used for Android development?", "answer": "kotlin",
     "difficulty": "hard"},
    {"question": "What is the capital of Slovenia?", "answer": "ljubljana", "difficulty": "hard"},
    {"question": "What is the cube root of 512?", "answer": "8", "difficulty": "hard"},
    {"question": "What is the name of the first artificial Earth satellite?", "answer": "sputnik 1",
     "difficulty": "hard"},
    {"question": "What is the chemical formula for ozone?", "answer": "o3", "difficulty": "hard"},
    {"question": "What is the SI unit of electric current?", "answer": "ampere", "difficulty": "hard"},
    {"question": "In which year was Python first released?", "answer": "1991", "difficulty": "hard"},
    {"question": "What is the capital of Liechtenstein?", "answer": "vaduz", "difficulty": "hard"},
    {"question": "What is the smallest prime number greater than 100?", "answer": "101", "difficulty": "hard"},
    {"question": "What is the chemical symbol for tungsten?", "answer": "w", "difficulty": "hard"},
    {"question": "Who formulated the uncertainty principle?", "answer": "heisenberg", "difficulty": "hard"},
    {"question": "What is the derivative of ln(x)?", "answer": "1/x", "difficulty": "hard"},
    {"question": "What is the hexadecimal representation of decimal 255?", "answer": "ff", "difficulty": "hard"},
    {"question": "What is the capital of Burkina Faso?", "answer": "ouagadougou", "difficulty": "hard"},
]
